### ISSUE TITLE
Allow binstubs path to be configurable

### ISSUE THREAD

**Issue by mikechau** [p0deje/vagrant-exec#11]
Since Rails 4 will also install local `binstubs`, I think it would be useful to provide an option to specify a different folder for the `binstubs` provided by `vagrant-exec`.

It would be nice if in the Vagrantfile, we could specify something like:

```ruby
config.exec.commands '*', directory: '/app', binstubs_path: '/vagrant'
config.exec.commands 'bundle'
config.exec.commands %w(rails rake), prepend: 'bundle exec'
```

And then the generated `binstubs` would be created inside the `binstubs_path`, `/vagrant`.

Thoughts?

**Comment by p0deje** [comment]
I think it might make sense, though I'd like to be able to just wrap Rails binstubs with our binstubs (e.g. like rails/spring does), but not sure if it's really possible.

In any case, I think it might make sense to allow binstubs be configurable, but with different way. Something like this would work:

```ruby
config.exec.binstubs_path = 'vbin/'
```

Patches are welcome!

**Comment by p0deje** [comment]
Release in 0.5.2. See usage example in comment above.
