### ISSUE TITLE
.bashrc alias doesn't work

### ISSUE THREAD

**Issue by peet86** [p0deje/vagrant-exec#14]
Hey,

It would be nice to run somehow alias commands on the guest.

So define something like this on the guest machine: (/home/vagrant/.bashrc)

`alias mycommand='/path/subpath/mycommand.sh -x -y -z && myothercommand - z - y -y'`

And run this on the host: 
vagrant execute mycommand

As I see this is not possible at the moment..  
When I run "vagrant exec mycommand"  I get this error: 

`bash: mycommand: command not found`

**Comment by p0deje** [comment]
That is probably similar to http://stackoverflow.com/questions/1198378/ssh-command-execution-doesnt-consider-bashrc-bash-login-ssh-rc, so you can try the suggested option. Otherwise, you can define such command in `Vagrantfile`.

Closing this for now, please reopen if issue persists.
