### ISSUE TITLE
Feature: Add option for complete command processing

### ISSUE THREAD

**Issue by majkinetor** [p0deje/vagrant-exec#9]
I would like to see an option to somehow preprocess entire command instead of just prepending some text to it.

For instance

<pre>
    # vagrant db-import executes /vagrant/db_import.sh
    node.exec.commands 'db-import', cmd: '/vagrant/db_import.sh'
    # remove .sh  and replace _ with - from bash scripts names
    node.exec.commands '*', modify: @cmd.gsub("_", "-").gsub(".sh", "");
</pre>

**Comment by etki** [comment]
I know i'm late for party, but i'm going to vote up for this.
I'm creating a default repository for corporate needs, so i need to do two things:
* Polish everything as much as possible
* Put as much as i can into configuration files so developers may feel safe to work with files, knowing that only restricted files are Vagrantfile, Dockerfile, .dockerignore, etc., but everything in /bin is in their posession.
So i've stumbled upon a need to create a shortcut like `vagrant test` to run tests in the box or `vagrant reinstall` to drop database and reinstall application, and command behind "run tests" may be as long as `bin/codecept run --debug --report --html --xml --coverage --coverage-xml --coverage-html --env=vagrant`, so there's no chance for not automatizing this. Currently i'm using a prepend hack (`command 'test', prepend: bin/codecept --options #`), but this, of course, is not a proper solution.

**Comment by p0deje** [comment]
Why not just create Rakefile for such kind of tasks? For example, `vagrant rake test`.

**Comment by etki** [comment]
@p0deje oh, sorry for not being explicit enough. I'm a PHP developer, so i don't know vagrant and things like ruby workflow well. I'll try Rakefile, thank you!

**Comment by p0deje** [comment]
@etki In PHP there are phing/phake.
